<a href="https://colab.research.google.com/github/azrapatvi/dl-practice/blob/main/10_hyper_parameter_tuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("jamaltariqcheema/pima-indians-diabetes-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'pima-indians-diabetes-dataset' dataset.
Path to dataset files: /kaggle/input/pima-indians-diabetes-dataset

In [4]:
import os

df=pd.read_csv(os.path.join(path,'diabetes.csv'))

In [5]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72.0,35,169.5,33.6,0.627,50,1
1,1,85,66.0,29,102.5,26.6,0.351,31,0
2,8,183,64.0,32,169.5,23.3,0.672,32,1
3,1,89,66.0,23,94.0,28.1,0.167,21,0
4,0,137,40.0,35,168.0,43.1,2.288,33,1

In [6]:
df.columns=df.columns.str.lower().str.strip()

In [7]:
X=df.drop('outcome',axis=1)
y=df['outcome']

In [8]:
df.shape

(768, 9)

In [9]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [10]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

In [11]:
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [12]:
X_train_scaled

array([[-0.85135507, -1.0568694 , -0.82668697, ..., -0.76615019,
         0.31079384, -0.79216928],
       [ 0.35657564,  0.1428554 ,  0.4770088 , ..., -0.41444809,
        -0.11643851,  0.56103382],
       [-0.5493724 , -0.55698407, -1.15261091, ...,  0.36222739,
        -0.76486207, -0.70759409],
       ...,
       [-0.85135507, -0.82358958, -0.17483909, ...,  0.83116352,
        -0.78607218, -0.28471812],
       [ 1.86648903, -0.35702994, -0.17483909, ..., -0.72218742,
        -1.01938346,  0.56103382],
       [ 0.05459296,  0.74271779, -1.15261091, ..., -0.42910234,
        -0.57700104,  0.30730824]])

In [13]:
X_train.shape[1]

8

In [14]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

model=Sequential([
    Dense(128,activation='relu',input_dim=X_train.shape[1]),
    Dense(1,activation='sigmoid')
])

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [15]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │         1,152 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,281 (5.00 KB)

 Trainable params: 1,281 (5.00 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

# so here we selected the optimizer on our own intiution soo dont know weather this will be best or nott soo thatswyhy we will use hyper paramter tuning to seelect the best optimizer

In [17]:
model.fit(X_train_scaled,y_train,epochs=100,batch_size=32,validation_data=(X_test_scaled,y_test),verbose=1)

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 57ms/step - accuracy: 0.7345 - loss: 0.5825 - val_accuracy: 0.7338 - val_loss: 0.5406
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4878 - val_accuracy: 0.7403 - val_loss: 0.4931
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4443 - val_accuracy: 0.7403 - val_loss: 0.4731
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4215 - val_accuracy: 0.7468 - val_loss: 0.4651
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.4089 - val_accuracy: 0.7468 - val_loss: 0.4617
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.4002 - val_accuracy: 0.7338 - val_loss: 0.4556
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3948 - val_accuracy: 0.7403 - val_loss: 0.4539
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3873 - val_accuracy: 0.7468 - val_loss: 0.4543
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3827 - val_accuracy: 0.7532 - val_loss: 0.4508
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3771 - val_accuracy: 0.7662 - val_loss: 0.4452
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3725 - val_accuracy: 0.7727 - val_loss: 0.4429
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3681 - val_accuracy: 0.7792 - val_loss: 0.4369
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3638 - val_accuracy: 0.7662 - val_loss: 0.4332
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3601 - val_accuracy: 0.7792 - val_loss: 0.4310
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3555 - val_accuracy: 0.7857 - val_loss: 0.4237
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3517 - val_accuracy: 0.7792 - val_loss: 0.4243
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8469 - loss: 0.3487 - val_accuracy: 0.7857 - val_loss: 0.4162
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8485 - loss: 0.3447 - val_accuracy: 0.7857 - val_loss: 0.4162
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8518 - loss: 0.3411 - val_accuracy: 0.7987 - val_loss: 0.4129
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8518 - loss: 0.3378 - val_accuracy: 0.7987 - val_loss: 0.4087
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8648 - loss: 0.3354 - val_accuracy: 0.8052 - val_loss: 0.4029
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8697 - loss: 0.3308 - val_accuracy: 0.8052 - val_loss: 0.4036
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8681 - loss: 0.3284 - val_accuracy: 0.8117 - val_loss: 0.4040
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8713 - loss: 0.3254 - val_accuracy: 0.7987 - val_loss: 0.3988
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8681 - loss: 0.3233 - val_accuracy: 0.8247 - val_loss: 0.3986
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8713 - loss: 0.3218 - val_accuracy: 0.8247 - val_loss: 0.3969
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8746 - loss: 0.3189 - val_accuracy: 0.8312 - val_loss: 0.3959
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8779 - loss: 0.3166 - val_accuracy: 0.8506 - val_loss: 0.3917
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8811 - loss: 0.3145 - val_accuracy: 0.8506 - val_loss: 0.3900
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8893 - loss: 0.3132 - val_accuracy: 0.8506 - val_loss: 0.3919
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8909 - loss: 0.3107 - val_accuracy: 0.8442 - val_loss: 0.3926
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8893 - loss: 0.3089 - val_accuracy: 0.8571 - val_loss: 0.3883
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8925 - loss: 0.3073 - val_accuracy: 0.8636 - val_loss: 0.3866
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8941 - loss: 0.3066 - val_accuracy: 0.8636 - val_loss: 0.3846
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8844 - loss: 0.3047 - val_accuracy: 0.8506 - val_loss: 0.3857
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8860 - loss: 0.3030 - val_accuracy: 0.8636 - val_loss: 0.3846
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8876 - loss: 0.3010 - val_accuracy: 0.8636 - val_loss: 0.3844
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8893 - loss: 0.3007 - val_accuracy: 0.8636 - val_loss: 0.3844
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8941 - loss: 0.2988 - val_accuracy: 0.8636 - val_loss: 0.3835
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8941 - loss: 0.2977 - val_accuracy: 0.8506 - val_loss: 0.3850
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8925 - loss: 0.2976 - val_accuracy: 0.8636 - val_loss: 0.3844
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8958 - loss: 0.2952 - val_accuracy: 0.8571 - val_loss: 0.3837
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8974 - loss: 0.2938 - val_accuracy: 0.8571 - val_loss: 0.3865
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8990 - loss: 0.2924 - val_accuracy: 0.8506 - val_loss: 0.3854
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8958 - loss: 0.2917 - val_accuracy: 0.8506 - val_loss: 0.3856
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8990 - loss: 0.2906 - val_accuracy: 0.8442 - val_loss: 0.3863
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8990 - loss: 0.2900 - val_accuracy: 0.8571 - val_loss: 0.3846
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8974 - loss: 0.2903 - val_accuracy: 0.8636 - val_loss: 0.3875
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8974 - loss: 0.2878 - val_accuracy: 0.8571 - val_loss: 0.3856
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8974 - loss: 0.2868 - val_accuracy: 0.8571 - val_loss: 0.3833
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8990 - loss: 0.2868 - val_accuracy: 0.8442 - val_loss: 0.3841
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8974 - loss: 0.2854 - val_accuracy: 0.8377 - val_loss: 0.3869
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9023 - loss: 0.2846 - val_accuracy: 0.8442 - val_loss: 0.3871
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9023 - loss: 0.2829 - val_accuracy: 0.8571 - val_loss: 0.3889
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9023 - loss: 0.2837 - val_accuracy: 0.8442 - val_loss: 0.3921
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8990 - loss: 0.2823 - val_accuracy: 0.8636 - val_loss: 0.3890
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8990 - loss: 0.2808 - val_accuracy: 0.8571 - val_loss: 0.3878
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8974 - loss: 0.2799 - val_accuracy: 0.8506 - val_loss: 0.3881
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9007 - loss: 0.2793 - val_accuracy: 0.8571 - val_loss: 0.3889
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9055 - loss: 0.2793 - val_accuracy: 0.8636 - val_loss: 0.3875
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9039 - loss: 0.2780 - val_accuracy: 0.8766 - val_loss: 0.3880
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9039 - loss: 0.2775 - val_accuracy: 0.8442 - val_loss: 0.3943
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9007 - loss: 0.2759 - val_accuracy: 0.8571 - val_loss: 0.3942
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9007 - loss: 0.2762 - val_accuracy: 0.8506 - val_loss: 0.3921
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9007 - loss: 0.2739 - val_accuracy: 0.8571 - val_loss: 0.3942
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9039 - loss: 0.2738 - val_accuracy: 0.8442 - val_loss: 0.3948
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2733 - val_accuracy: 0.8506 - val_loss: 0.3968
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9007 - loss: 0.2719 - val_accuracy: 0.8442 - val_loss: 0.3958
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9039 - loss: 0.2715 - val_accuracy: 0.8571 - val_loss: 0.3975
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2707 - val_accuracy: 0.8442 - val_loss: 0.4007
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9007 - loss: 0.2701 - val_accuracy: 0.8506 - val_loss: 0.3965
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9007 - loss: 0.2692 - val_accuracy: 0.8377 - val_loss: 0.4016
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2682 - val_accuracy: 0.8377 - val_loss: 0.4009
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2683 - val_accuracy: 0.8571 - val_loss: 0.4000
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2675 - val_accuracy: 0.8571 - val_loss: 0.3989
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9007 - loss: 0.2669 - val_accuracy: 0.8442 - val_loss: 0.4020
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9055 - loss: 0.2660 - val_accuracy: 0.8571 - val_loss: 0.3993
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9055 - loss: 0.2646 - val_accuracy: 0.8571 - val_loss: 0.3993
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9072 - loss: 0.2649 - val_accuracy: 0.8636 - val_loss: 0.3986
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9055 - loss: 0.2638 - val_accuracy: 0.8506 - val_loss: 0.4003
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9072 - loss: 0.2635 - val_accuracy: 0.8571 - val_loss: 0.4048
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2628 - val_accuracy: 0.8442 - val_loss: 0.4033
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2612 - val_accuracy: 0.8571 - val_loss: 0.3997
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9055 - loss: 0.2616 - val_accuracy: 0.8571 - val_loss: 0.4037
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9055 - loss: 0.2608 - val_accuracy: 0.8571 - val_loss: 0.4048
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9088 - loss: 0.2603 - val_accuracy: 0.8442 - val_loss: 0.4081
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9055 - loss: 0.2605 - val_accuracy: 0.8571 - val_loss: 0.4039
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9039 - loss: 0.2594 - val_accuracy: 0.8571 - val_loss: 0.4043
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9072 - loss: 0.2590 - val_accuracy: 0.8442 - val_loss: 0.4011
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9055 - loss: 0.2576 - val_accuracy: 0.8571 - val_loss: 0.4012
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9039 - loss: 0.2576 - val_accuracy: 0.8636 - val_loss: 0.4003
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9039 - loss: 0.2584 - val_accuracy: 0.8506 - val_loss: 0.3993
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9039 - loss: 0.2556 - val_accuracy: 0.8506 - val_loss: 0.4030
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9039 - loss: 0.2566 - val_accuracy: 0.8377 - val_loss: 0.4006
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9072 - loss: 0.2548 - val_accuracy: 0.8571 - val_loss: 0.4039
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9055 - loss: 0.2553 - val_accuracy: 0.8442 - val_loss: 0.4056
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9104 - loss: 0.2549 - val_accuracy: 0.8506 - val_loss: 0.4029
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9121 - loss: 0.2540 - val_accuracy: 0.8506 - val_loss: 0.4041
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9104 - loss: 0.2531 - val_accuracy: 0.8442 - val_loss: 0.4068
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9121 - loss: 0.2521 - val_accuracy: 0.8571 - val_loss: 0.4101

In [18]:
df.head(2)

,pregnancies,glucose,bloodpressure,skinthickness,insulin,bmi,diabetespedigreefunction,age,outcome
0,6,148,72.0,35,169.5,33.6,0.627,50,1
1,1,85,66.0,29,102.5,26.6,0.351,31,0

In [19]:
!pip install keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (26.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (2.32.4)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (1.83.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.13/dist-packages (from grpcio->keras-tuner) (4.16.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (2.1.3)
Requirement already satisfied: rich in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (0.20.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (0.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (2026.7.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras->keras-tuner) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras->keras-tuner) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 13.3 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

In [20]:
# select an optimizer

import kerastuner as kt

/tmp/ipykernel_3917/3126251022.py:3: DeprecationWarning: `import kerastuner` is deprecated, please use `import keras_tuner`.
  import kerastuner as kt

In [21]:
# create a function

def build_model(hp):

  model=Sequential()

  model.add(Dense(128,activation='relu',input_dim=X_train.shape[1]))

  model.add(Dense(1,activation='sigmoid'))


  optimizer=hp.Choice('optimizer',['adam','rmsprop','sgd','adagrad'])

  model.compile(optimizer=optimizer,loss='binary_crossentropy',metrics=['accuracy'])

  return model

In [22]:
# create an object of keras tuner for hyper paramter tunign

tuner=kt.RandomSearch(build_model,
                      objective='val_accuracy',
                      max_trials=5)

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [23]:
tuner

In [24]:
tuner.search(X_train_scaled,y_train,epochs=10,validation_data=(X_test_scaled,y_test))

Trial 4 Complete [00h 00m 05s]
val_accuracy: 0.6818181872367859

Best val_accuracy So Far: 0.7727272510528564
Total elapsed time: 00h 00m 26s

In [25]:
tuner.results_summary()

Results summary
Results in ./untitled_project
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 1 summary
Hyperparameters:
optimizer: rmsprop
Score: 0.7727272510528564

Trial 0 summary
Hyperparameters:
optimizer: adam
Score: 0.7532467246055603

Trial 2 summary
Hyperparameters:
optimizer: sgd
Score: 0.7272727489471436

Trial 3 summary
Hyperparameters:
optimizer: adagrad
Score: 0.6818181872367859

In [26]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [27]:
tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.13/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [28]:
model=tuner.get_best_models(num_models=1)[0]

In [29]:
model.optimizer

In [30]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │         1,152 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,281 (5.00 KB)

 Trainable params: 1,281 (5.00 KB)

 Non-trainable params: 0 (0.00 B)

In [31]:
model.fit(X_train_scaled,y_train,epochs=100,batch_size=32,validation_data=(X_test_scaled,y_test),verbose=1)

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 45ms/step - accuracy: 0.8094 - loss: 0.4825 - val_accuracy: 0.7532 - val_loss: 0.4813
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4381 - val_accuracy: 0.7468 - val_loss: 0.4643
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4175 - val_accuracy: 0.7338 - val_loss: 0.4592
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.4052 - val_accuracy: 0.7468 - val_loss: 0.4584
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3972 - val_accuracy: 0.7532 - val_loss: 0.4565
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8257 - loss: 0.3894 - val_accuracy: 0.7468 - val_loss: 0.4482
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3835 - val_accuracy: 0.7532 - val_loss: 0.4436
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3781 - val_accuracy: 0.7597 - val_loss: 0.4398
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3732 - val_accuracy: 0.7597 - val_loss: 0.4372
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8339 - loss: 0.3687 - val_accuracy: 0.7532 - val_loss: 0.4341
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8371 - loss: 0.3641 - val_accuracy: 0.7727 - val_loss: 0.4286
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8420 - loss: 0.3599 - val_accuracy: 0.7727 - val_loss: 0.4240
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8436 - loss: 0.3556 - val_accuracy: 0.7727 - val_loss: 0.4229
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8469 - loss: 0.3525 - val_accuracy: 0.7857 - val_loss: 0.4219
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8453 - loss: 0.3486 - val_accuracy: 0.7987 - val_loss: 0.4160
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8534 - loss: 0.3443 - val_accuracy: 0.7987 - val_loss: 0.4086
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8534 - loss: 0.3407 - val_accuracy: 0.8117 - val_loss: 0.4045
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8583 - loss: 0.3375 - val_accuracy: 0.8117 - val_loss: 0.4023
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8599 - loss: 0.3342 - val_accuracy: 0.8182 - val_loss: 0.4006
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8632 - loss: 0.3307 - val_accuracy: 0.8247 - val_loss: 0.3987
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8648 - loss: 0.3286 - val_accuracy: 0.8247 - val_loss: 0.4037
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8746 - loss: 0.3263 - val_accuracy: 0.8377 - val_loss: 0.3988
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - loss: 0.3244 - val_accuracy: 0.8377 - val_loss: 0.3916
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8811 - loss: 0.3219 - val_accuracy: 0.8442 - val_loss: 0.3878
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8746 - loss: 0.3198 - val_accuracy: 0.8377 - val_loss: 0.3866
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8811 - loss: 0.3179 - val_accuracy: 0.8442 - val_loss: 0.3847
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8746 - loss: 0.3159 - val_accuracy: 0.8571 - val_loss: 0.3866
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8827 - loss: 0.3141 - val_accuracy: 0.8571 - val_loss: 0.3863
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8811 - loss: 0.3122 - val_accuracy: 0.8506 - val_loss: 0.3870
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8827 - loss: 0.3105 - val_accuracy: 0.8506 - val_loss: 0.3859
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8827 - loss: 0.3095 - val_accuracy: 0.8571 - val_loss: 0.3847
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8876 - loss: 0.3077 - val_accuracy: 0.8571 - val_loss: 0.3855
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8860 - loss: 0.3068 - val_accuracy: 0.8571 - val_loss: 0.3837
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8844 - loss: 0.3049 - val_accuracy: 0.8442 - val_loss: 0.3848
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8893 - loss: 0.3046 - val_accuracy: 0.8571 - val_loss: 0.3853
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8844 - loss: 0.3022 - val_accuracy: 0.8506 - val_loss: 0.3832
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8844 - loss: 0.3016 - val_accuracy: 0.8506 - val_loss: 0.3821
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8893 - loss: 0.3005 - val_accuracy: 0.8506 - val_loss: 0.3836
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8893 - loss: 0.2994 - val_accuracy: 0.8571 - val_loss: 0.3834
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8876 - loss: 0.2989 - val_accuracy: 0.8571 - val_loss: 0.3813
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8893 - loss: 0.2974 - val_accuracy: 0.8571 - val_loss: 0.3850
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8909 - loss: 0.2960 - val_accuracy: 0.8571 - val_loss: 0.3813
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8925 - loss: 0.2948 - val_accuracy: 0.8571 - val_loss: 0.3825
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8925 - loss: 0.2942 - val_accuracy: 0.8571 - val_loss: 0.3841
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8925 - loss: 0.2939 - val_accuracy: 0.8442 - val_loss: 0.3849
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8925 - loss: 0.2917 - val_accuracy: 0.8571 - val_loss: 0.3851
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8958 - loss: 0.2918 - val_accuracy: 0.8571 - val_loss: 0.3860
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8909 - loss: 0.2907 - val_accuracy: 0.8571 - val_loss: 0.3857
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8909 - loss: 0.2899 - val_accuracy: 0.8571 - val_loss: 0.3840
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8941 - loss: 0.2883 - val_accuracy: 0.8506 - val_loss: 0.3863
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8958 - loss: 0.2884 - val_accuracy: 0.8506 - val_loss: 0.3901
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8909 - loss: 0.2874 - val_accuracy: 0.8506 - val_loss: 0.3896
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8941 - loss: 0.2865 - val_accuracy: 0.8506 - val_loss: 0.3885
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8941 - loss: 0.2857 - val_accuracy: 0.8442 - val_loss: 0.3875
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2848 - val_accuracy: 0.8506 - val_loss: 0.3911
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8958 - loss: 0.2844 - val_accuracy: 0.8442 - val_loss: 0.3913
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8974 - loss: 0.2828 - val_accuracy: 0.8506 - val_loss: 0.3889
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9007 - loss: 0.2821 - val_accuracy: 0.8442 - val_loss: 0.3911
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8990 - loss: 0.2821 - val_accuracy: 0.8506 - val_loss: 0.3885
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8974 - loss: 0.2813 - val_accuracy: 0.8506 - val_loss: 0.3886
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9007 - loss: 0.2796 - val_accuracy: 0.8377 - val_loss: 0.3900
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9007 - loss: 0.2796 - val_accuracy: 0.8442 - val_loss: 0.3884
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8990 - loss: 0.2786 - val_accuracy: 0.8442 - val_loss: 0.3905
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2780 - val_accuracy: 0.8442 - val_loss: 0.3936
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8990 - loss: 0.2783 - val_accuracy: 0.8442 - val_loss: 0.3931
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8974 - loss: 0.2766 - val_accuracy: 0.8377 - val_loss: 0.3930
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8990 - loss: 0.2763 - val_accuracy: 0.8377 - val_loss: 0.3932
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9039 - loss: 0.2745 - val_accuracy: 0.8377 - val_loss: 0.3966
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2755 - val_accuracy: 0.8442 - val_loss: 0.3954
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2740 - val_accuracy: 0.8506 - val_loss: 0.3986
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2739 - val_accuracy: 0.8377 - val_loss: 0.3970
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9039 - loss: 0.2732 - val_accuracy: 0.8377 - val_loss: 0.3986
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2731 - val_accuracy: 0.8377 - val_loss: 0.3975
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9007 - loss: 0.2723 - val_accuracy: 0.8506 - val_loss: 0.4018
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2716 - val_accuracy: 0.8377 - val_loss: 0.3987
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8990 - loss: 0.2707 - val_accuracy: 0.8377 - val_loss: 0.3988
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9039 - loss: 0.2706 - val_accuracy: 0.8442 - val_loss: 0.3996
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9007 - loss: 0.2690 - val_accuracy: 0.8377 - val_loss: 0.4021
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2690 - val_accuracy: 0.8377 - val_loss: 0.4007
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2691 - val_accuracy: 0.8377 - val_loss: 0.4051
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2675 - val_accuracy: 0.8377 - val_loss: 0.4013
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9072 - loss: 0.2673 - val_accuracy: 0.8377 - val_loss: 0.4004
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8990 - loss: 0.2676 - val_accuracy: 0.8377 - val_loss: 0.4036
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9055 - loss: 0.2663 - val_accuracy: 0.8506 - val_loss: 0.4012
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9039 - loss: 0.2657 - val_accuracy: 0.8506 - val_loss: 0.4007
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9104 - loss: 0.2655 - val_accuracy: 0.8442 - val_loss: 0.4009
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9072 - loss: 0.2648 - val_accuracy: 0.8442 - val_loss: 0.3997
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9088 - loss: 0.2649 - val_accuracy: 0.8506 - val_loss: 0.3995
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9072 - loss: 0.2639 - val_accuracy: 0.8506 - val_loss: 0.3990
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9088 - loss: 0.2633 - val_accuracy: 0.8506 - val_loss: 0.3942
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9072 - loss: 0.2623 - val_accuracy: 0.8506 - val_loss: 0.4020
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9039 - loss: 0.2637 - val_accuracy: 0.8506 - val_loss: 0.3991
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9072 - loss: 0.2625 - val_accuracy: 0.8442 - val_loss: 0.4023
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9072 - loss: 0.2628 - val_accuracy: 0.8442 - val_loss: 0.4027
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9088 - loss: 0.2606 - val_accuracy: 0.8442 - val_loss: 0.4027
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9055 - loss: 0.2615 - val_accuracy: 0.8442 - val_loss: 0.4009
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9121 - loss: 0.2596 - val_accuracy: 0.8442 - val_loss: 0.4046
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9088 - loss: 0.2599 - val_accuracy: 0.8442 - val_loss: 0.4059
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9104 - loss: 0.2582 - val_accuracy: 0.8442 - val_loss: 0.4074
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9104 - loss: 0.2588 - val_accuracy: 0.8442 - val_loss: 0.4070

In [32]:
# hyper paramter tuning for deciding the neurons in the first hiddn layer

def build_model(hp):

  model=Sequential()

  units=hp.Int('units',min_value=8,max_value=128) #,step=8) # menas increametn by 8 neurons 8 16 24 till 128

  model.add(Dense(units=units,activation='relu',input_dim=X_train.shape[1]))

  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])

  return model

In [33]:
tuner=kt.RandomSearch(build_model,
                      objective='val_accuracy',
                      max_trials=5,
                      directory='untitled2')

In [34]:
X_test_scaled

array([[ 0.96054099,  1.24260312, -0.663725  , ..., -0.73684168,
        -0.55579092,  0.56103382],
       [ 1.86648903, -1.79003455,  2.7584764 , ...,  0.45015291,
        -0.58306107,  1.15306018],
       [-0.5493724 ,  0.00955264,  0.31404683, ...,  0.50876993,
         0.01688223, -0.6230189 ],
       ...,
       [-0.5493724 , -1.32347491, -1.64149683, ..., -0.57564488,
         3.70138246, -0.70759409],
       [ 0.05459296,  2.07574534,  0.4770088 , ...,  0.66996673,
        -0.64669142, -0.20014293],
       [-0.85135507, -1.69005749,  0.4770088 , ...,  0.11310507,
        -0.16794879, -1.04589487]])

In [35]:
tuner.search(X_train_scaled,y_train,epochs=10,validation_data=(X_test_scaled,y_test))

Trial 5 Complete [00h 00m 05s]
val_accuracy: 0.7597402334213257

Best val_accuracy So Far: 0.7727272510528564
Total elapsed time: 00h 00m 31s

In [36]:
tuner.results_summary()

Results summary
Results in untitled2/untitled_project
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 3 summary
Hyperparameters:
units: 89
Score: 0.7727272510528564

Trial 4 summary
Hyperparameters:
units: 95
Score: 0.7597402334213257

Trial 1 summary
Hyperparameters:
units: 45
Score: 0.7532467246055603

Trial 0 summary
Hyperparameters:
units: 57
Score: 0.7467532753944397

Trial 2 summary
Hyperparameters:
units: 10
Score: 0.7467532753944397

In [37]:
tuner.get_best_hyperparameters()[0].values

{'units': 89}

In [38]:
model=tuner.get_best_models(num_models=1)[0]

In [39]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 89)             │           801 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            90 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 891 (3.48 KB)

 Trainable params: 891 (3.48 KB)

 Non-trainable params: 0 (0.00 B)

In [40]:
model.fit(X_train_scaled,y_train,epochs=100,initial_epoch=6)

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.7980 - loss: 0.4431
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8078 - loss: 0.4221
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8046 - loss: 0.4104
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8127 - loss: 0.4031
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8143 - loss: 0.3960
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8192 - loss: 0.3903
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8176 - loss: 0.3850
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8241 - loss: 0.3807
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8241 - loss: 0.3757
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8290 - loss: 0.3711
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8339 - loss: 0.3666
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8371 - loss: 0.3626
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8371 - loss: 0.3594
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8355 - loss: 0.3553
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8388 - loss: 0.3520
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8436 - loss: 0.3480
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8453 - loss: 0.3445
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8436 - loss: 0.3411
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8583 - loss: 0.3377
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8599 - loss: 0.3346
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8664 - loss: 0.3313
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8664 - loss: 0.3291
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8713 - loss: 0.3263
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8730 - loss: 0.3239
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8762 - loss: 0.3216
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8811 - loss: 0.3187
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8779 - loss: 0.3181
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8909 - loss: 0.3144
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8844 - loss: 0.3137
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8844 - loss: 0.3114
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8893 - loss: 0.3097
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8893 - loss: 0.3085
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8876 - loss: 0.3069
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8909 - loss: 0.3053
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8925 - loss: 0.3040
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8909 - loss: 0.3022
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8893 - loss: 0.3010
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8925 - loss: 0.2998
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8925 - loss: 0.2986
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8941 - loss: 0.2974
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8893 - loss: 0.2971
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8941 - loss: 0.2962
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8909 - loss: 0.2945
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8958 - loss: 0.2940
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8958 - loss: 0.2924
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8925 - loss: 0.2924
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8925 - loss: 0.2914
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8909 - loss: 0.2908
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8925 - loss: 0.2898
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8909 - loss: 0.2886
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8909 - loss: 0.2882
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8941 - loss: 0.2876
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8941 - loss: 0.2863
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8941 - loss: 0.2861
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8941 - loss: 0.2847
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8941 - loss: 0.2849
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8941 - loss: 0.2832
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8925 - loss: 0.2833
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8958 - loss: 0.2824
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8925 - loss: 0.2817
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9023 - loss: 0.2805
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8974 - loss: 0.2804
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8958 - loss: 0.2805
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8958 - loss: 0.2795
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8974 - loss: 0.2784
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9023 - loss: 0.2782
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9039 - loss: 0.2779
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9023 - loss: 0.2772
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9007 - loss: 0.2767
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9023 - loss: 0.2760
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9007 - loss: 0.2758
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8990 - loss: 0.2748
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9007 - loss: 0.2742
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9023 - loss: 0.2733
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9007 - loss: 0.2739
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9023 - loss: 0.2728
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9023 - loss: 0.2720
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9023 - loss: 0.2723
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9007 - loss: 0.2715
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9023 - loss: 0.2716
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9039 - loss: 0.2703
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9023 - loss: 0.2695
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9055 - loss: 0.2693
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9039 - loss: 0.2685
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9055 - loss: 0.2686
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9023 - loss: 0.2686
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8990 - loss: 0.2671
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9023 - loss: 0.2669
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9023 - loss: 0.2666
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9039 - loss: 0.2661
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9023 - loss: 0.2654
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9039 - loss: 0.2651
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9121 - loss: 0.2642
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9072 - loss: 0.2644

In [41]:
# hyper praamter tuning for deciding number of layers

def build_model(hp):

  model=Sequential()

  model.add(Dense(56,activation='relu',input_dim=X_train.shape[1]))

  for i in range(hp.Int("num_layers",min_value=1,max_value=10)):
    model.add(Dense(32,activation='relu'))

  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

  return model

In [42]:
tuner=kt.RandomSearch(build_model,
                      objective='val_accuracy',
                      max_trials=5,
                      directory='untitled3')

In [43]:
tuner.search(X_train_scaled,y_train,epochs=10,validation_data=(X_test_scaled,y_test))

Trial 5 Complete [00h 00m 05s]
val_accuracy: 0.8441558480262756

Best val_accuracy So Far: 0.8441558480262756
Total elapsed time: 00h 00m 35s

In [44]:
tuner.results_summary()

Results summary
Results in untitled3/untitled_project
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 0 summary
Hyperparameters:
num_layers: 9
Score: 0.8441558480262756

Trial 4 summary
Hyperparameters:
num_layers: 3
Score: 0.8441558480262756

Trial 3 summary
Hyperparameters:
num_layers: 10
Score: 0.8311688303947449

Trial 1 summary
Hyperparameters:
num_layers: 2
Score: 0.8246753215789795

Trial 2 summary
Hyperparameters:
num_layers: 7
Score: 0.8246753215789795

In [45]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 9}

In [57]:
# now creating a full function to select parameters for layers neurons and function

def build_model(hp):

  model=Sequential()

  counter=0

  for i in range(hp.Int('units',min_value=1,max_value=10)): # lets say it is selecting 2 so for i in rnage(2) #0,1

    if counter==0:
      model.add(
          Dense(
              hp.Int('neurons'+str(i),min_value=8,max_value=128),
              activation=hp.Choice('activation'+str(i),values=['relu','tanh','sigmoid']),
              input_dim=X_train.shape[1]
              )
          )

    else:
      model.add(
          Dense(
              hp.Int('neurons'+str(i),min_value=8,max_value=128),
              activation=hp.Choice('activation'+str(i),values=['relu','tanh','sigmoid'])
          )
      )

    counter+=1

  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer=hp.Choice('optimizer',values=['adam','rmsprop','sgd','adagrad']),
                loss='binary_crossentropy',
                metrics=['accuracy'])

  return model

In [58]:
tuner=kt.RandomSearch(build_model,
                      objective='val_accuracy',
                      max_trials=10,
                      directory='full_tuner3')

In [59]:
tuner.search(X_train_scaled,y_train,epochs=50,validation_data=(X_test_scaled,y_test))

Trial 10 Complete [00h 00m 13s]
val_accuracy: 0.649350643157959

Best val_accuracy So Far: 0.8701298832893372
Total elapsed time: 00h 02m 20s

In [60]:
tuner.results_summary()

Results summary
Results in full_tuner3/untitled_project
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 08 summary
Hyperparameters:
units: 7
neurons0: 114
activation0: sigmoid
optimizer: adam
neurons1: 53
activation1: tanh
neurons2: 25
activation2: sigmoid
neurons3: 95
activation3: relu
neurons4: 43
activation4: tanh
neurons5: 51
activation5: tanh
neurons6: 110
activation6: tanh
neurons7: 34
activation7: relu
neurons8: 13
activation8: sigmoid
neurons9: 120
activation9: sigmoid
Score: 0.8701298832893372

Trial 02 summary
Hyperparameters:
units: 2
neurons0: 120
activation0: relu
optimizer: rmsprop
neurons1: 68
activation1: sigmoid
neurons2: 38
activation2: relu
neurons3: 13
activation3: tanh
neurons4: 87
activation4: sigmoid
neurons5: 107
activation5: relu
neurons6: 34
activation6: relu
neurons7: 107
activation7: tanh
neurons8: 101
activation8: relu
neurons9: 120
activation9: relu
Score: 0.8571428656578064

Trial 03 summary
Hyperparameters:
units: 7
neurons0: 11
activation0: tanh
optimizer: rmsprop
neurons1: 47
activation1: tanh
neurons2: 58
activation2: relu
neurons3: 27
activation3: relu
neurons4: 79
activation4: relu
neurons5: 125
activation5: tanh
neurons6: 32
activation6: tanh
neurons7: 127
activation7: tanh
neurons8: 72
activation8: relu
neurons9: 56
activation9: relu
Score: 0.8571428656578064

Trial 00 summary
Hyperparameters:
units: 5
neurons0: 14
activation0: tanh
optimizer: sgd
neurons1: 8
activation1: relu
neurons2: 8
activation2: relu
neurons3: 8
activation3: relu
neurons4: 8
activation4: relu
Score: 0.7792207598686218

Trial 04 summary
Hyperparameters:
units: 2
neurons0: 52
activation0: sigmoid
optimizer: rmsprop
neurons1: 74
activation1: sigmoid
neurons2: 57
activation2: relu
neurons3: 31
activation3: relu
neurons4: 12
activation4: tanh
neurons5: 36
activation5: relu
neurons6: 117
activation6: sigmoid
neurons7: 98
activation7: relu
neurons8: 124
activation8: relu
neurons9: 95
activation9: tanh
Score: 0.7662337422370911

Trial 06 summary
Hyperparameters:
units: 2
neurons0: 28
activation0: sigmoid
optimizer: adam
neurons1: 121
activation1: sigmoid
neurons2: 67
activation2: sigmoid
neurons3: 116
activation3: tanh
neurons4: 90
activation4: sigmoid
neurons5: 39
activation5: tanh
neurons6: 21
activation6: sigmoid
neurons7: 85
activation7: tanh
neurons8: 28
activation8: tanh
neurons9: 26
activation9: sigmoid
Score: 0.7597402334213257

Trial 01 summary
Hyperparameters:
units: 10
neurons0: 83
activation0: tanh
optimizer: adagrad
neurons1: 88
activation1: tanh
neurons2: 67
activation2: tanh
neurons3: 53
activation3: sigmoid
neurons4: 52
activation4: relu
neurons5: 8
activation5: relu
neurons6: 8
activation6: relu
neurons7: 8
activation7: relu
neurons8: 8
activation8: relu
neurons9: 8
activation9: relu
Score: 0.649350643157959

Trial 05 summary
Hyperparameters:
units: 3
neurons0: 40
activation0: relu
optimizer: adagrad
neurons1: 38
activation1: sigmoid
neurons2: 40
activation2: relu
neurons3: 126
activation3: sigmoid
neurons4: 48
activation4: relu
neurons5: 125
activation5: tanh
neurons6: 82
activation6: sigmoid
neurons7: 119
activation7: tanh
neurons8: 90
activation8: tanh
neurons9: 72
activation9: tanh
Score: 0.649350643157959

Trial 07 summary
Hyperparameters:
units: 5
neurons0: 73
activation0: sigmoid
optimizer: sgd
neurons1: 21
activation1: relu
neurons2: 9
activation2: tanh
neurons3: 27
activation3: sigmoid
neurons4: 106
activation4: sigmoid
neurons5: 81
activation5: sigmoid
neurons6: 20
activation6: relu
neurons7: 126
activation7: relu
neurons8: 108
activation8: sigmoid
neurons9: 126
activation9: sigmoid
Score: 0.649350643157959

Trial 09 summary
Hyperparameters:
units: 6
neurons0: 10
activation0: tanh
optimizer: sgd
neurons1: 31
activation1: sigmoid
neurons2: 10
activation2: sigmoid
neurons3: 9
activation3: sigmoid
neurons4: 79
activation4: sigmoid
neurons5: 71
activation5: sigmoid
neurons6: 121
activation6: sigmoid
neurons7: 25
activation7: relu
neurons8: 82
activation8: relu
neurons9: 26
activation9: sigmoid
Score: 0.649350643157959

In [66]:
model=tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.13/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 34 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [67]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 114)            │         1,026 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 53)             │         6,095 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 25)             │         1,350 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 95)             │         2,470 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 43)             │         4,128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 51)             │         2,244 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 110)            │         5,720 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │           111 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 23,144 (90.41 KB)

 Trainable params: 23,144 (90.41 KB)

 Non-trainable params: 0 (0.00 B)

In [68]:
from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

model.fit(
    X_train_scaled,
    y_train,
    epochs=500,
    validation_data=(X_test_scaled, y_test)
)

Epoch 1/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 6s 146ms/step - accuracy: 0.8599 - loss: 0.3426 - val_accuracy: 0.8442 - val_loss: 0.3650
Epoch 2/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8664 - loss: 0.3157 - val_accuracy: 0.8701 - val_loss: 0.3684
Epoch 3/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8632 - loss: 0.3225 - val_accuracy: 0.8377 - val_loss: 0.3790
Epoch 4/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8762 - loss: 0.3187 - val_accuracy: 0.8636 - val_loss: 0.3643
Epoch 5/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8827 - loss: 0.3223 - val_accuracy: 0.8506 - val_loss: 0.3583
Epoch 6/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8779 - loss: 0.3184 - val_accuracy: 0.8377 - val_loss: 0.3763
Epoch 7/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8762 - loss: 0.3127 - val_accuracy: 0.8442 - val_loss: 0.3590
Epoch 8/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8632 - loss: 0.3340 - val_accuracy: 0.8701 - val_loss: 0.3559
Epoch 9/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8746 - loss: 0.3148 - val_accuracy: 0.8506 - val_loss: 0.3674
Epoch 10/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8779 - loss: 0.3114 - val_accuracy: 0.8766 - val_loss: 0.3598
Epoch 11/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8893 - loss: 0.3052 - val_accuracy: 0.8442 - val_loss: 0.3807
Epoch 12/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8664 - loss: 0.3125 - val_accuracy: 0.8506 - val_loss: 0.3873
Epoch 13/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8697 - loss: 0.3226 - val_accuracy: 0.8247 - val_loss: 0.4037
Epoch 14/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8616 - loss: 0.3467 - val_accuracy: 0.8636 - val_loss: 0.3592
Epoch 15/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8762 - loss: 0.3054 - val_accuracy: 0.8312 - val_loss: 0.3676
Epoch 16/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8795 - loss: 0.3059 - val_accuracy: 0.8377 - val_loss: 0.3739
Epoch 17/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8746 - loss: 0.3102 - val_accuracy: 0.8377 - val_loss: 0.3707
Epoch 18/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8762 - loss: 0.3080 - val_accuracy: 0.8506 - val_loss: 0.3559
Epoch 19/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8730 - loss: 0.3122 - val_accuracy: 0.8571 - val_loss: 0.3596
Epoch 20/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8762 - loss: 0.3054 - val_accuracy: 0.8831 - val_loss: 0.3473
Epoch 21/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8795 - loss: 0.3020 - val_accuracy: 0.8506 - val_loss: 0.3558
Epoch 22/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8779 - loss: 0.2977 - val_accuracy: 0.8636 - val_loss: 0.3480
Epoch 23/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8827 - loss: 0.2943 - val_accuracy: 0.8571 - val_loss: 0.3674
Epoch 24/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8746 - loss: 0.3052 - val_accuracy: 0.8571 - val_loss: 0.3591
Epoch 25/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8730 - loss: 0.2958 - val_accuracy: 0.8636 - val_loss: 0.3632
Epoch 26/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8844 - loss: 0.3079 - val_accuracy: 0.8442 - val_loss: 0.3672
Epoch 27/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8779 - loss: 0.2981 - val_accuracy: 0.8636 - val_loss: 0.3644
Epoch 28/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8860 - loss: 0.3019 - val_accuracy: 0.8442 - val_loss: 0.3772
Epoch 29/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8713 - loss: 0.3349 - val_accuracy: 0.8571 - val_loss: 0.3655
Epoch 30/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8925 - loss: 0.2959 - val_accuracy: 0.8377 - val_loss: 0.3661
Epoch 31/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8795 - loss: 0.3013 - val_accuracy: 0.8571 - val_loss: 0.3542
Epoch 32/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8844 - loss: 0.2953 - val_accuracy: 0.8442 - val_loss: 0.3670
Epoch 33/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8860 - loss: 0.2899 - val_accuracy: 0.8636 - val_loss: 0.3558
Epoch 34/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8925 - loss: 0.2931 - val_accuracy: 0.8571 - val_loss: 0.3560
Epoch 35/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8811 - loss: 0.2910 - val_accuracy: 0.8571 - val_loss: 0.3652
Epoch 36/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8762 - loss: 0.2903 - val_accuracy: 0.8636 - val_loss: 0.3678
Epoch 37/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8827 - loss: 0.2903 - val_accuracy: 0.8442 - val_loss: 0.3665
Epoch 38/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8664 - loss: 0.3050 - val_accuracy: 0.8571 - val_loss: 0.3548
Epoch 39/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8893 - loss: 0.2835 - val_accuracy: 0.8636 - val_loss: 0.3993
Epoch 40/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8746 - loss: 0.2914 - val_accuracy: 0.8506 - val_loss: 0.3676
Epoch 41/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8876 - loss: 0.2971 - val_accuracy: 0.8377 - val_loss: 0.4099
Epoch 42/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8860 - loss: 0.2915 - val_accuracy: 0.8442 - val_loss: 0.3829
Epoch 43/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8827 - loss: 0.2963 - val_accuracy: 0.8442 - val_loss: 0.3671
Epoch 44/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8795 - loss: 0.2931 - val_accuracy: 0.8506 - val_loss: 0.3495
Epoch 45/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8811 - loss: 0.3037 - val_accuracy: 0.8571 - val_loss: 0.3817
Epoch 46/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8860 - loss: 0.2850 - val_accuracy: 0.8571 - val_loss: 0.3555
Epoch 47/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8827 - loss: 0.2843 - val_accuracy: 0.8506 - val_loss: 0.3549
Epoch 48/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8811 - loss: 0.2918 - val_accuracy: 0.8442 - val_loss: 0.4004
Epoch 49/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8958 - loss: 0.2907 - val_accuracy: 0.8571 - val_loss: 0.3638
Epoch 50/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8697 - loss: 0.3010 - val_accuracy: 0.8506 - val_loss: 0.3695
Epoch 51/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8958 - loss: 0.2827 - val_accuracy: 0.8442 - val_loss: 0.3613
Epoch 52/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8909 - loss: 0.2712 - val_accuracy: 0.8442 - val_loss: 0.3603
Epoch 53/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8860 - loss: 0.3024 - val_accuracy: 0.7922 - val_loss: 0.4588
Epoch 54/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8844 - loss: 0.2904 - val_accuracy: 0.8442 - val_loss: 0.3840
Epoch 55/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8893 - loss: 0.2773 - val_accuracy: 0.8506 - val_loss: 0.3748
Epoch 56/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8876 - loss: 0.2812 - val_accuracy: 0.8442 - val_loss: 0.3586
Epoch 57/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8827 - loss: 0.2894 - val_accuracy: 0.8442 - val_loss: 0.3749
Epoch 58/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8876 - loss: 0.2720 - val_accuracy: 0.8442 - val_loss: 0.3736
Epoch 59/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8811 - loss: 0.2812 - val_accuracy: 0.8506 - val_loss: 0.3710
Epoch 60/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8909 - loss: 0.2758 - val_accuracy: 0.8506 - val_loss: 0.3684
Epoch 61/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8860 - loss: 0.2778 - val_accuracy: 0.8571 - val_loss: 0.3982
Epoch 62/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8876 - loss: 0.2951 - val_accuracy: 0.8571 - val_loss: 0.3541
Epoch 63/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8844 - loss: 0.2808 - val_accuracy: 0.8571 - val_loss: 0.3585
Epoch 64/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8909 - loss: 0.2651 - val_accuracy: 0.8312 - val_loss: 0.4098
Epoch 65/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8909 - loss: 0.2709 - val_accuracy: 0.8442 - val_loss: 0.4057
Epoch 66/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8730 - loss: 0.2993 - val_accuracy: 0.8312 - val_loss: 0.4278
Epoch 67/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8844 - loss: 0.2937 - val_accuracy: 0.8506 - val_loss: 0.3807
Epoch 68/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8827 - loss: 0.2767 - val_accuracy: 0.8506 - val_loss: 0.3720
Epoch 69/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8876 - loss: 0.2792 - val_accuracy: 0.8636 - val_loss: 0.3868
Epoch 70/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8827 - loss: 0.2811 - val_accuracy: 0.8506 - val_loss: 0.3641
Epoch 71/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8958 - loss: 0.2594 - val_accuracy: 0.8377 - val_loss: 0.4066
Epoch 72/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8909 - loss: 0.2564 - val_accuracy: 0.8506 - val_loss: 0.3890
Epoch 73/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8697 - loss: 0.3046 - val_accuracy: 0.8701 - val_loss: 0.3645
Epoch 74/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8811 - loss: 0.2645 - val_accuracy: 0.8312 - val_loss: 0.3749
Epoch 75/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8876 - loss: 0.2830 - val_accuracy: 0.8636 - val_loss: 0.3776
Epoch 76/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8844 - loss: 0.2717 - val_accuracy: 0.8636 - val_loss: 0.3842
Epoch 77/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8860 - loss: 0.2759 - val_accuracy: 0.8506 - val_loss: 0.3778
Epoch 78/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8827 - loss: 0.2728 - val_accuracy: 0.8571 - val_loss: 0.3675
Epoch 79/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8876 - loss: 0.2781 - val_accuracy: 0.8571 - val_loss: 0.3885
Epoch 80/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8860 - loss: 0.2731 - val_accuracy: 0.8506 - val_loss: 0.3565
Epoch 81/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8844 - loss: 0.2715 - val_accuracy: 0.8506 - val_loss: 0.3734
Epoch 82/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8779 - loss: 0.2897 - val_accuracy: 0.8312 - val_loss: 0.4075
Epoch 83/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8893 - loss: 0.2659 - val_accuracy: 0.8506 - val_loss: 0.3695
Epoch 84/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8909 - loss: 0.2893 - val_accuracy: 0.8506 - val_loss: 0.3775
Epoch 85/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8876 - loss: 0.2652 - val_accuracy: 0.8442 - val_loss: 0.3730
Epoch 86/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8925 - loss: 0.2622 - val_accuracy: 0.8442 - val_loss: 0.3697
Epoch 87/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8844 - loss: 0.2753 - val_accuracy: 0.8312 - val_loss: 0.3893
Epoch 88/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8941 - loss: 0.2520 - val_accuracy: 0.8442 - val_loss: 0.3672
Epoch 89/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8974 - loss: 0.2471 - val_accuracy: 0.8312 - val_loss: 0.3850
Epoch 90/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8762 - loss: 0.2610 - val_accuracy: 0.8442 - val_loss: 0.3707
Epoch 91/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8925 - loss: 0.2479 - val_accuracy: 0.8377 - val_loss: 0.3803
Epoch 92/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8893 - loss: 0.2705 - val_accuracy: 0.8506 - val_loss: 0.3457
Epoch 93/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8958 - loss: 0.2607 - val_accuracy: 0.8506 - val_loss: 0.3732
Epoch 94/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9007 - loss: 0.2527 - val_accuracy: 0.8377 - val_loss: 0.3719
Epoch 95/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8925 - loss: 0.2490 - val_accuracy: 0.8377 - val_loss: 0.3755
Epoch 96/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8876 - loss: 0.2588 - val_accuracy: 0.8506 - val_loss: 0.3979
Epoch 97/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8909 - loss: 0.2466 - val_accuracy: 0.8377 - val_loss: 0.3850
Epoch 98/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8941 - loss: 0.2443 - val_accuracy: 0.8571 - val_loss: 0.3642
Epoch 99/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8779 - loss: 0.2560 - val_accuracy: 0.8506 - val_loss: 0.3862
Epoch 100/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8893 - loss: 0.2484 - val_accuracy: 0.8636 - val_loss: 0.3931
Epoch 101/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8893 - loss: 0.2667 - val_accuracy: 0.8506 - val_loss: 0.3858
Epoch 102/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9007 - loss: 0.2443 - val_accuracy: 0.8506 - val_loss: 0.3881
Epoch 103/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8941 - loss: 0.2450 - val_accuracy: 0.8442 - val_loss: 0.3795
Epoch 104/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8893 - loss: 0.2464 - val_accuracy: 0.8377 - val_loss: 0.3976
Epoch 105/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8893 - loss: 0.2424 - val_accuracy: 0.8442 - val_loss: 0.3679
Epoch 106/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8958 - loss: 0.2386 - val_accuracy: 0.8506 - val_loss: 0.3955
Epoch 107/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8827 - loss: 0.2483 - val_accuracy: 0.8442 - val_loss: 0.3969
Epoch 108/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8762 - loss: 0.2689 - val_accuracy: 0.8571 - val_loss: 0.4048
Epoch 109/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8860 - loss: 0.2604 - val_accuracy: 0.8506 - val_loss: 0.3703
Epoch 110/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8844 - loss: 0.2476 - val_accuracy: 0.8571 - val_loss: 0.3698
Epoch 111/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8876 - loss: 0.2485 - val_accuracy: 0.8636 - val_loss: 0.3652
Epoch 112/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8941 - loss: 0.2451 - val_accuracy: 0.8506 - val_loss: 0.3979
Epoch 113/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8909 - loss: 0.2472 - val_accuracy: 0.8571 - val_loss: 0.4061
Epoch 114/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8827 - loss: 0.2640 - val_accuracy: 0.7922 - val_loss: 0.4249
Epoch 115/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8827 - loss: 0.2614 - val_accuracy: 0.8377 - val_loss: 0.3952
Epoch 116/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8974 - loss: 0.2519 - val_accuracy: 0.8377 - val_loss: 0.4091
Epoch 117/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8909 - loss: 0.2585 - val_accuracy: 0.8442 - val_loss: 0.4194
Epoch 118/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8909 - loss: 0.2482 - val_accuracy: 0.8377 - val_loss: 0.3932
Epoch 119/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8974 - loss: 0.2323 - val_accuracy: 0.8571 - val_loss: 0.3813
Epoch 120/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8909 - loss: 0.2328 - val_accuracy: 0.8506 - val_loss: 0.3945
Epoch 121/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8746 - loss: 0.2600 - val_accuracy: 0.8831 - val_loss: 0.3634
Epoch 122/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8941 - loss: 0.2403 - val_accuracy: 0.8506 - val_loss: 0.3939
Epoch 123/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8909 - loss: 0.2414 - val_accuracy: 0.8442 - val_loss: 0.3807
Epoch 124/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8925 - loss: 0.2407 - val_accuracy: 0.8506 - val_loss: 0.3834
Epoch 125/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8876 - loss: 0.2445 - val_accuracy: 0.8442 - val_loss: 0.3942
Epoch 126/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8941 - loss: 0.2351 - val_accuracy: 0.8442 - val_loss: 0.4043
Epoch 127/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8827 - loss: 0.2620 - val_accuracy: 0.8506 - val_loss: 0.3771
Epoch 128/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8941 - loss: 0.2392 - val_accuracy: 0.8571 - val_loss: 0.3880
Epoch 129/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8909 - loss: 0.2318 - val_accuracy: 0.8636 - val_loss: 0.4257
Epoch 130/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8844 - loss: 0.2527 - val_accuracy: 0.8377 - val_loss: 0.3847
Epoch 131/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8974 - loss: 0.2282 - val_accuracy: 0.8636 - val_loss: 0.3982
Epoch 132/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8941 - loss: 0.2360 - val_accuracy: 0.8506 - val_loss: 0.3914
Epoch 133/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8909 - loss: 0.2351 - val_accuracy: 0.8571 - val_loss: 0.3933
Epoch 134/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9023 - loss: 0.2212 - val_accuracy: 0.8506 - val_loss: 0.4093
Epoch 135/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8941 - loss: 0.2410 - val_accuracy: 0.8701 - val_loss: 0.3827
Epoch 136/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8941 - loss: 0.2249 - val_accuracy: 0.8442 - val_loss: 0.4115
Epoch 137/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8990 - loss: 0.2185 - val_accuracy: 0.8571 - val_loss: 0.4269
Epoch 138/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8925 - loss: 0.2363 - val_accuracy: 0.8636 - val_loss: 0.3733
Epoch 139/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8827 - loss: 0.2388 - val_accuracy: 0.8636 - val_loss: 0.3816
Epoch 140/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8844 - loss: 0.2676 - val_accuracy: 0.8701 - val_loss: 0.3904
Epoch 141/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8990 - loss: 0.2378 - val_accuracy: 0.8312 - val_loss: 0.4022
Epoch 142/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8876 - loss: 0.2297 - val_accuracy: 0.8571 - val_loss: 0.3902
Epoch 143/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8990 - loss: 0.2203 - val_accuracy: 0.8506 - val_loss: 0.3967
Epoch 144/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9055 - loss: 0.2173 - val_accuracy: 0.8636 - val_loss: 0.4272
Epoch 145/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8974 - loss: 0.2240 - val_accuracy: 0.8636 - val_loss: 0.3915
Epoch 146/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8958 - loss: 0.2145 - val_accuracy: 0.8701 - val_loss: 0.4162
Epoch 147/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9023 - loss: 0.2287 - val_accuracy: 0.8571 - val_loss: 0.3887
Epoch 148/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8958 - loss: 0.2210 - val_accuracy: 0.8571 - val_loss: 0.3939
Epoch 149/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9007 - loss: 0.2117 - val_accuracy: 0.8506 - val_loss: 0.4119
Epoch 150/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8941 - loss: 0.2210 - val_accuracy: 0.8312 - val_loss: 0.4336
Epoch 151/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9007 - loss: 0.2129 - val_accuracy: 0.8506 - val_loss: 0.4264
Epoch 152/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8974 - loss: 0.2136 - val_accuracy: 0.8506 - val_loss: 0.4295
Epoch 153/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9039 - loss: 0.2159 - val_accuracy: 0.8766 - val_loss: 0.4090
Epoch 154/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8990 - loss: 0.2206 - val_accuracy: 0.8701 - val_loss: 0.4164
Epoch 155/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9023 - loss: 0.2353 - val_accuracy: 0.8571 - val_loss: 0.4264
Epoch 156/500

In [69]:
X_train

,pregnancies,glucose,bloodpressure,skinthickness,insulin,bmi,diabetespedigreefunction,age
353,1,90,62.0,12,43.0,27.2,0.580,24
711,5,126,78.0,27,22.0,29.6,0.439,40
373,2,105,58.0,40,94.0,34.9,0.225,25
46,1,146,56.0,27,102.5,29.7,0.564,29
682,0,95,64.0,39,105.0,44.6,0.366,22
...,...,...,...,...,...,...,...,...
451,2,134,70.0,32,169.5,28.9,0.542,23
113,4,76,62.0,27,102.5,34.0,0.391,25
556,1,97,70.0,40,102.5,38.1,0.218,30
667,10,111,70.0,27,169.5,27.5,0.141,40
107,4,144,58.0,28,140.0,29.5,0.287,37

In [76]:
import pandas as pd

new_data = pd.DataFrame({
    'pregnancies': [1, 5],
    'glucose': [90, 126],
    'bloodpressure': [62.0, 78.0],
    'skinthickness': [12, 27],
    'insulin': [43.0, 22.0],
    'bmi': [27.2, 29.6],
    'diabetespedigreefunction': [0.580, 0.439],
    'age': [24, 40]
})

new_data

,pregnancies,glucose,bloodpressure,skinthickness,insulin,bmi,diabetespedigreefunction,age
0,1,90,62.0,12,43.0,27.2,0.580,24
1,5,126,78.0,27,22.0,29.6,0.439,40

In [72]:
X_train.head(2)

,pregnancies,glucose,bloodpressure,skinthickness,insulin,bmi,diabetespedigreefunction,age
353,1,90,62.0,12,43.0,27.2,0.580,24
711,5,126,78.0,27,22.0,29.6,0.439,40

In [75]:
scaler

StandardScaler()

In [77]:
new_data_scaled=scaler.transform(new_data)

In [78]:
new_data_scaled

array([[-0.85135507, -1.0568694 , -0.82668697, -1.8952899 , -1.17037761,
        -0.76615019,  0.31079384, -0.79216928],
       [ 0.35657564,  0.1428554 ,  0.4770088 , -0.22473578, -1.42764161,
        -0.41444809, -0.11643851,  0.56103382]])

In [80]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 114)            │         1,026 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 53)             │         6,095 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 25)             │         1,350 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 95)             │         2,470 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 43)             │         4,128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 51)             │         2,244 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 110)            │         5,720 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │           111 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 69,434 (271.23 KB)

 Trainable params: 23,144 (90.41 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 46,290 (180.82 KB)

In [84]:
new_data_pred=model.predict(new_data_scaled)

print(f"Prediction: {new_data_pred[0][0]:.6f}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step
Prediction: 0.000024

In [85]:
import pandas as pd

new_data = pd.DataFrame([
    [6, 148, 72, 35, 190, 33.6, 0.627, 50],
    [8, 170, 74, 30, 185, 35.2, 0.650, 45],
    [4, 160, 80, 40, 210, 38.5, 0.750, 52]
], columns=X_train.columns)

new_data

,pregnancies,glucose,bloodpressure,skinthickness,insulin,bmi,diabetespedigreefunction,age
0,6,148,72,35,190,33.6,0.627,50
1,8,170,74,30,185,35.2,0.650,45
2,4,160,80,40,210,38.5,0.750,52

In [86]:
new_data_scaled = scaler.transform(new_data)

prediction = model.predict(new_data_scaled)

for p in prediction:
    print(f"Prediction Probability: {p[0]:.6f}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 771ms/step
Prediction Probability: 0.249230
Prediction Probability: 0.999903
Prediction Probability: 0.999607

In [87]:
for p in prediction:
    if p[0] >= 0.5:
        print(f"{p[0]:.6f} → Diabetic prediction")
    else:
        print(f"{p[0]:.6f} → Not Diabetic prediction")

0.249230 → Not Diabetic prediction
0.999903 → Diabetic prediction
0.999607 → Diabetic prediction